version: "3.9"
services:
  db-node-1:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: pzjqUkMnc7vfNHET
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    ports:
      - 3360:3306
    volumes:
      - db-node-1-data:/var/lib/mysql

  db-node-2:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: pzjqUkMnc7vfNHET
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    ports:
      - 3361:3306
    volumes:
      - db-node-2-data:/var/lib/mysql

  proxysql:
    build:
      context: docker/proxysql
      dockerfile: Dockerfile
    volumes:
      - proxysql-data:/var/lib/proxysql
    ports:
      # Mysql Client Port
      - "6033:6033"
      # Mysql Admin Port
      - "6032:6032"

volumes:
  db-node-1-data:
  db-node-2-data:
  proxysql-data: