version: "3.9"
services:
  app:
    env_file:
      - ./.env
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    command: air -c .air.toml
    ports:
      - ${APP_PORT}:${APP_PORT}
      - ${PROM_PORT}:${PROM_PORT} # prometheus
    environment:
      - LDFLAGS=${LDFLAGS}
    volumes:
      - .:/app

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${MY_DB_NAME}
      MYSQL_PASSWORD: ${MY_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MY_PASSWORD}
      MYSQL_TCP_PORT: ${MY_PORT}
    ports:
      - ${MY_PORT}:${MY_PORT}
    volumes:
      - mysql-data:/var/lib/mysql

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - ${PROM_GUI_PORT}:${PROM_GUI_PORT}
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
  mysql-data:
